#pragma once

extern unsigned long processId;

extern uintptr_t clientDll;
extern uintptr_t engineDll;

extern uintptr_t clientstate;

extern uintptr_t localPlayer;
extern uintptr_t entityList;

extern uintptr_t entities[64];

enum BoneList
{
	BONE_PELVIS,
	BONE_SPINE1,
	BONE_SPINE2,
	BONE_SPINE3,
	BONE_SPINE4,
	BONE_NECK,
	BONE_L_CLAVICLE,
	BONE_L_UPPER_ARM,
	BONE_L_FOREARM,
	BONE_L_HAND,
	BONE_HEAD,
	BONE_FORWARD,
	BONE_R_CLAVICLE,
	BONE_R_UPPER_ARM,
	BONE_R_FOREARM,
	BONE_R_HAND,
	BONE_WEAPON,
	BONE_WEAPON_SLIDE,
	BONE_WEAPON_R_HAND,
	BONE_WEAPON_L_HAND,
	BONE_WEAPON_CLIP1,
	BONE_WEAPON_CLIP2,
	BONE_SILENCER,
	BONE_R_THIGH,
	BONE_R_CALF,
	BONE_R_FOOT,
	BONE_L_THIGH,
	BONE_L_CALF,
	BONE_L_FOOT,
	BONE_L_WEAPON_HAND,
	BONE_R_WEAPON_HAND,
	BONE_L_FORETWIST,
	BONE_L_CALFTWIST,
	BONE_R_CALFTWIST,
	BONE_L_THIGHTWIST,
	BONE_R_THIGHTWIST,
	BONE_L_UPARMTWIST,
	BONE_R_UPARMTWIST,
	BONE_R_FORETWIST,
	BONE_R_TOE,
	BONE_L_TOE,
	BONE_R_FINGER01,
	BONE_R_FINGER02,
	BONE_R_FINGER03,
	BONE_R_FINGER04,
	BONE_R_FINGER05,
	BONE_R_FINGER06,
	BONE_R_FINGER07,
	BONE_R_FINGER08,
	BONE_R_FINGER09,
	BONE_R_FINGER10,
	BONE_R_FINGER11,
	BONE_R_FINGER12,
	BONE_R_FINGER13,
	BONE_R_FINGER14,
	BONE_L_FINGER01,
	BONE_L_FINGER02,
	BONE_L_FINGER03,
	BONE_L_FINGER04,
	BONE_L_FINGER05,
	BONE_L_FINGER06,
	BONE_L_FINGER07,
	BONE_L_FINGER08,
	BONE_L_FINGER09,
	BONE_L_FINGER10,
	BONE_L_FINGER11,
	BONE_L_FINGER12,
	BONE_L_FINGER13,
	BONE_L_FINGER14,
	BONE_L_FINGER15,
	BONE_R_FINGER15,
	BONE_MAX
};